import { useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, TextInput, View } from 'react-native';
import { StitchHeader } from '@/components/stitch-header';
import { C, Page, Photo, Pill, StitchIcon, Text } from '@/components/stitch-ui';
import { RouteState } from '@/components/route-state';
import { demoRepository } from '@/data/demo-repository';
import { stitchAssets } from '@/data/stitch-assets';
import { activityPhoto, stitchCatalog } from '@/data/stitch-catalog';
import { getAvailableSlots, isChildEligibleForActivity } from '@/domain/booking-rules';
import { formatVenueDate, formatVenueTime } from '@/lib/datetime';
import { formatActivityPrice } from '@/lib/currency';
import { useLoadState } from '@/lib/use-load-state';

export default function ChooseSessionScreen() {
  const router = useRouter();
  const { activityId, sessionId: initialSessionId } = useLocalSearchParams<{ activityId: string; sessionId?: string }>();
  const { value: state, status, reload } = useLoadState(useCallback(() => demoRepository.getState(), []));
  const [sessionId, setSessionId] = useState<string | null>(initialSessionId || null);
  const [childId, setChildId] = useState<string | null>(null);
  const [notes, setNotes] = useState('');
  const activity = state?.activities.find(item => item.id === activityId);
  const sessions = state?.sessions.filter(item => item.activityId === activityId && new Date(item.startsAt) > new Date()) || [];
  const children = state?.children.filter(child => child.id === 'child_leo' || child.id === 'child_maya') || [];
  const selectedSession = sessions.find(item => item.id === sessionId);
  const selectedChild = children.find(item => item.id === childId);
  const price = formatActivityPrice(activity?.priceMinor || 2400, activity?.currency || 'USD', 2);
  const item = stitchCatalog.find(item => item.id === activityId);
  if (status === 'error' || (status === 'ready' && !activity)) return <RouteState kind="error" title="Sessions unavailable" description="Please try loading these sessions again." onAction={reload} />;
  const continueBooking = () => { if (selectedSession && selectedChild) router.push({ pathname: '/activity/[activityId]/review', params: { activityId, sessionId: selectedSession.id, childId: selectedChild.id, notes } }); };
  return <Page header={<StitchHeader section="Choose booking details" backLabel="Back to activity" />} footer={<View className="gap-2"><Pressable accessibilityRole="button" accessibilityLabel="Review booking" disabled={!selectedSession || !selectedChild} onPress={continueBooking} className="min-h-12 px-4 py-3 rounded-xl bg-[#EE5E41] flex-row items-center justify-between gap-2 active:opacity-70"><View className="flex-row items-center gap-2"><StitchIcon name="arrow_forward" color="#FFF" size={18} /><Text className="text-sm font-semibold text-white">Review booking</Text></View><Text className="text-sm font-semibold text-white">{price}</Text></Pressable><Text className="text-[11px] leading-4 text-center text-[#7C736E]">Choose a session and child before continuing.</Text></View>}>
    <View className="px-4 pt-3 pb-6 gap-5">
      <View className="rounded-2xl border border-[#EBE4DE] bg-white overflow-hidden"><View><Photo source={activityId === 'act_forest' ? stitchAssets.playnest_session_booking_child_selection[2] : activityPhoto(activityId)} height={160} /><View className="absolute top-3 left-3"><Pill tone="white" icon="eco">Sensory & Nature</Pill></View></View><View className="p-4 gap-3"><View className="gap-1"><View className="flex-row items-center gap-1.5"><StitchIcon name="location_on" size={16} color={C.primary} /><Text className="text-xs font-semibold tracking-wide text-[#EE5E41]">{activityId === 'act_forest' ? 'The Willow Studio • Room 2B' : activity?.locationName}</Text></View><Text className="text-lg leading-[25px] font-bold tracking-tight">{activity?.name || 'Loading activity…'}</Text></View><View className="pt-1 border-t border-[#EBE4DE99] flex-row flex-wrap gap-4"><View className="flex-row items-center gap-1.5"><StitchIcon name="calendar_today" size={18} color={C.primary} /><Text className="text-sm font-semibold">{selectedSession ? formatVenueDate(selectedSession.startsAt) : 'Choose a session'}</Text></View><View className="flex-row items-center gap-1.5"><StitchIcon name="schedule" size={18} color={C.primary} /><Text className="text-sm font-semibold">{selectedSession ? formatVenueTime(selectedSession.startsAt) : '—'}</Text></View></View></View></View>
      <View className="gap-3"><View className="flex-row items-center justify-between"><Text className="text-base font-bold">Choose a child</Text><Text className="text-xs text-[#7C736E]">One child per booking</Text></View><View className="gap-2.5">{children.map((child, i) => { const eligible = activity && isChildEligibleForActivity(child, activity, new Date()); const selected = selectedChild?.id === child.id; return <Pressable key={child.id} accessibilityRole="radio" accessibilityState={{ selected, disabled: !eligible }} disabled={!eligible} onPress={() => setChildId(child.id)} style={{ borderRadius: 16, borderWidth: selected ? 2 : 1, borderColor: selected ? C.primary : C.border, padding: 14, backgroundColor: eligible ? '#FFF' : '#F6F3F0', flexDirection: 'row', alignItems: 'center', gap: 12 }}><View style={{ width: 48, height: 48, borderRadius: 24, backgroundColor: i === 0 ? '#FFDAD3' : '#F4EDE6', alignItems: 'center', justifyContent: 'center' }}><Text style={{ fontSize: 18, fontWeight: "700", color: i === 0 ? "#8C1802" : "#59413C" }}>{child.firstName[0]}</Text></View><View className="flex-1"><Text className="text-sm font-bold">{child.firstName}</Text><View className="mt-1"><Pill fontSize={11} tone={eligible ? 'mint' : 'soft'}>{eligible ? 'Eligible for this activity' : `Ages ${item?.age || `${activity?.minAge}–${activity?.maxAge}`} only`}</Pill></View></View><View style={{ width: 28, height: 28, borderRadius: 14, backgroundColor: selected ? C.primary : '#F6F3F0', borderWidth: selected ? 0 : 1, borderColor: C.border, alignItems: 'center', justifyContent: 'center' }}>{selected ? <StitchIcon name="check" size={18} color="#FFF" /> : null}</View></Pressable>; })}</View></View>
      <View className="gap-3"><View className="flex-row justify-between"><Text className="text-base font-bold">Available Sessions</Text><Text className="text-xs font-semibold text-[#EE5E41]">Local Studio Time</Text></View><View className="gap-2.5">{sessions.map((session, i) => { const count = getAvailableSlots(session, state?.bookings || []); const selected = selectedSession?.id === session.id; return <Pressable key={session.id} accessibilityRole="radio" accessibilityState={{ selected, disabled: !count }} disabled={!count} onPress={() => setSessionId(session.id)} style={{ padding: 14, borderRadius: 16, borderWidth: selected ? 2 : 1, borderColor: selected ? C.primary : C.border, backgroundColor: selected ? C.primary : count ? '#FFF' : '#F6F3F0', gap: 8 }}><View className="flex-row items-center justify-between"><Text style={{ fontSize: 14, lineHeight: 20, fontWeight: '700', color: selected ? '#FFF' : C.ink }}>{formatVenueTime(session.startsAt)}</Text><Pill tone={count ? 'cream' : 'soft'}>{count ? `${count} spots left` : 'Full'}</Pill></View><Text style={{ fontSize: 12, lineHeight: 16, color: selected ? '#FFFFFFE6' : C.muted }}>{activity?.durationMinutes} mins • {['Gentle Start', 'Daylight Play', 'Wind Down'][i % 3]}</Text></Pressable>; })}</View>{!sessions.length && status === 'ready' ? <Text className="text-sm text-[#7C736E]">No future sessions are available.</Text> : null}</View>
      <View className="gap-2"><View className="flex-row justify-between"><View className="flex-row items-center gap-1.5"><StitchIcon name="spa" size={18} color={C.primary} /><Text className="text-sm font-bold">Care details</Text></View><Text className="text-xs text-[#7C736E]">Optional</Text></View><TextInput accessibilityLabel="Care details" multiline value={notes} onChangeText={setNotes} placeholder="e.g., Sensitive to loud sounds or prefers low-light corners..." placeholderTextColor="#8D716BB3" style={{ minHeight: 100, borderWidth: 1, borderColor: C.border, borderRadius: 16, backgroundColor: '#FFF', padding: 14, fontSize: 14, lineHeight: 20, fontFamily: 'Jakarta', textAlignVertical: 'top' }} /><Text className="text-xs leading-4 text-[#7C736E]">Saved only with this local demo reservation.</Text></View>
      <View className="p-4 rounded-2xl border border-[#EBE4DE] bg-white gap-3"><View className="pb-2 border-b border-[#EBE4DE] flex-row justify-between"><Text className="text-sm font-bold">Order Summary</Text><Text className="text-xs font-semibold text-[#EE5E41]">Local demo booking</Text></View><View className="flex-row justify-between"><Text className="text-sm">Session Fee (1 Explorer)</Text><Text className="text-sm font-bold">{price}</Text></View><View className="flex-row justify-between"><Text className="text-xs text-[#59413C]">Organic tactile kit & materials</Text><Pill>Included</Pill></View><View className="flex-row justify-between"><Text className="text-xs text-[#59413C]">Studio environmental sanitization</Text><Text className="text-xs font-semibold text-[#215954]">$0.00</Text></View><View className="p-3 mt-1 bg-[#FCFAF7] rounded-xl border border-[#EBE4DE] flex-row items-center justify-between"><View><Text className="text-sm font-bold">Total Due</Text><Text className="text-[11px] text-[#7C736E]">Taxes included</Text></View><Text className="text-xl font-bold text-[#EE5E41]">{price}</Text></View></View>
      <View className="p-4 rounded-2xl border border-[#D5E6E5] bg-[#EAF8F6] flex-row items-start gap-3"><StitchIcon name="info" size={24} color={C.teal} /><View className="flex-1"><Text className="text-sm font-bold text-[#215954]">What this demo proves</Text><Text className="mt-0.5 text-xs leading-5 text-[#59413C]">Eligibility and remaining spots are checked again when you save the reservation.</Text></View></View>
    </View>
  </Page>;
}
